version: "2"
services:
  unifi-controller:
    image: unifi:latest
    container_name: unifi-controller
    environment:
      - USER="unifi" # default
      - JAVA_OPTS="" # default
    volumes:
      - /unifi/data:/usr/lib/unifi/data
      - /unifi/logs:/usr/lib/unifi/logs
      - /unifi/run:/usr/lib/unifi/run
    ports:
      - 3478:3478/udp   # Unifi communication port
      - 10001:10001/udp # required for AP discovery
      - 8080:8080       # required for Unifi to function
      - 8081:8081       # Unifi communication port
      - 443:8443        # Unifi webapp communication port
      - 8843:8843       # Unifi communication port
      - 8880:8880       # Unifi communication port
      - 6789:6789       # for throughput test
    restart: unless-stopped

